/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/osmancevik/PX4-Autopilot/msg/EstimatorAidSource1d.msg */


#include <inttypes.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/defines.h>
#include <uORB/topics/estimator_aid_source1d.h>
#include <uORB/topics/uORBTopics.hpp>
#include <drivers/drv_hrt.h>
#include <lib/drivers/device/Device.hpp>
#include <lib/matrix/matrix/math.hpp>
#include <lib/mathlib/mathlib.h>


static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_baro_hgt) == 50, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_baro_hgt, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_baro_hgt), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_ev_hgt) == 52, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_ev_hgt, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_ev_hgt), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_gnss_hgt) == 58, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_gnss_hgt, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_gnss_hgt), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_rng_hgt) == 65, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_rng_hgt, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_rng_hgt), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_airspeed) == 47, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_airspeed, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_airspeed), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_sideslip) == 66, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_sideslip, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_sideslip), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_fake_hgt) == 56, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_fake_hgt, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_fake_hgt), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_gnss_yaw) == 61, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_gnss_yaw, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_gnss_yaw), 1);
static_assert(static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_ev_yaw) == 55, "ORB_ID index mismatch");
ORB_DEFINE(estimator_aid_src_ev_yaw, struct estimator_aid_source1d_s, 59, 4008362038u, static_cast<orb_id_size_t>(ORB_ID::estimator_aid_src_ev_yaw), 1);


void print_message(const orb_metadata *meta, const estimator_aid_source1d_s& message)
{
	if (sizeof(message) != meta->o_size) {
		printf("unexpected message size for %s: %zu != %i\n", meta->o_name, sizeof(message), meta->o_size);
		return;
	}
	orb_print_message_internal(meta, &message, true);
}
