/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/osmancevik/PX4-Autopilot/src/drivers/uavcan/libdronecan/dsdl/dronecan/sensors/magnetometer/1043.MagneticFieldStrengthHiRes.uavcan
 */

#ifndef DRONECAN_SENSORS_MAGNETOMETER_MAGNETICFIELDSTRENGTHHIRES_HPP_INCLUDED
#define DRONECAN_SENSORS_MAGNETOMETER_MAGNETICFIELDSTRENGTHHIRES_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Magnetic field readings, in Gauss, in body frame, high resolution version

uint8 sensor_id
float32[3] magnetic_field_ga
******************************************************************************/

/********************* DSDL signature source definition ***********************
dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes
saturated uint8 sensor_id
saturated float32[3] magnetic_field_ga
******************************************************************************/

#undef sensor_id
#undef magnetic_field_ga

namespace dronecan
{
namespace sensors
{
namespace magnetometer
{

template <int _tmpl>
struct UAVCAN_EXPORT MagneticFieldStrengthHiRes_
{
    typedef const MagneticFieldStrengthHiRes_<_tmpl>& ParameterType;
    typedef MagneticFieldStrengthHiRes_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > sensor_id;
        typedef ::uavcan::Array< ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeStatic, 3 > magnetic_field_ga;
    };

    enum
    {
        MinBitLen
            = FieldTypes::sensor_id::MinBitLen
            + FieldTypes::magnetic_field_ga::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::sensor_id::MaxBitLen
            + FieldTypes::magnetic_field_ga::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::sensor_id >::Type sensor_id;
    typename ::uavcan::StorageType< typename FieldTypes::magnetic_field_ga >::Type magnetic_field_ga;

    MagneticFieldStrengthHiRes_()
        : sensor_id()
        , magnetic_field_ga()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<104 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 1043 };

    static const char* getDataTypeFullName()
    {
        return "dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool MagneticFieldStrengthHiRes_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        sensor_id == rhs.sensor_id &&
        magnetic_field_ga == rhs.magnetic_field_ga;
}

template <int _tmpl>
bool MagneticFieldStrengthHiRes_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(sensor_id, rhs.sensor_id) &&
        ::uavcan::areClose(magnetic_field_ga, rhs.magnetic_field_ga);
}

template <int _tmpl>
int MagneticFieldStrengthHiRes_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::sensor_id::encode(self.sensor_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::magnetic_field_ga::encode(self.magnetic_field_ga, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int MagneticFieldStrengthHiRes_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::sensor_id::decode(self.sensor_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::magnetic_field_ga::decode(self.magnetic_field_ga, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature MagneticFieldStrengthHiRes_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x3053EBE3D750286FULL);

    FieldTypes::sensor_id::extendDataTypeSignature(signature);
    FieldTypes::magnetic_field_ga::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef MagneticFieldStrengthHiRes_<0> MagneticFieldStrengthHiRes;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes > _uavcan_gdtr_registrator_MagneticFieldStrengthHiRes;

}

} // Namespace magnetometer
} // Namespace sensors
} // Namespace dronecan

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes >::stream(Stream& s, ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "sensor_id: ";
    YamlStreamer< ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes::FieldTypes::sensor_id >::stream(s, obj.sensor_id, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "magnetic_field_ga: ";
    YamlStreamer< ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes::FieldTypes::magnetic_field_ga >::stream(s, obj.magnetic_field_ga, level + 1);
}

}

namespace dronecan
{
namespace sensors
{
namespace magnetometer
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::dronecan::sensors::magnetometer::MagneticFieldStrengthHiRes >::stream(s, obj, 0);
    return s;
}

} // Namespace magnetometer
} // Namespace sensors
} // Namespace dronecan

#endif // DRONECAN_SENSORS_MAGNETOMETER_MAGNETICFIELDSTRENGTHHIRES_HPP_INCLUDED