services:
  swarm_dev_amd:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Kullanıcı yapılandırması. create-docker.sh tarafından otomatik doldurulur.
        USERNAME: yelpence
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}

    image: yelpence_swarm_amd:2026
    container_name: yelpence_swarm_container_amd

    # SSH bağlantısı için port ayarı.
    port:
      - "2222:22"

    network_mode: host
    ipc: host
    pid: host
    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=43
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - LIBGL_ALWAYS_SOFTWARE=0
      - GZ_SIM_RENDER_ENGINE_BACKEND=ogre2
      - MESA_LOADER_DRIVER_OVERRIDE=radeonsi
      - GALLIUM_DRIVER=radeonsi

    # Host ile konteyner arasında bağlanmış dizinler.
    # DİKKAT! src/ dizinini asla mount etmeyin. Örneğin src/swarm gibi spesifik mountlar yapın.
    # src/ mount edilirse PX4 Autopilot kodları silinir.
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../src/swarm:/home/yelpence/ros2_ws/src/swarm
      - ../scripts:/home/yelpence/ros2_ws/scripts
      - ../sim:/home/yelpence/ros2_ws/sim
      - ../src/requirements.txt:/home/yelpence/ros2_ws/src/requirements.txt:ro

    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyAMA0:/dev/ttyAMA0

    group_add:
      - video
      - render

    stdin_open: true
    tty: true
    command: /bin/bash
