services:
  swarm_dev_amd:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # Kullanıcı yapılandırması. create-docker.sh tarafından otomatik doldurulur.
        USERNAME: yelpence
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}

    image: yelpence_swarm_amd:2026
    container_name: yelpence_swarm_container_amd

    # SSH bağlantısı için port ayarı.
    ports:
      - "2222:22"

    network_mode: host
    ipc: host
    pid: host
    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=43
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - LIBGL_ALWAYS_SOFTWARE=0
      - GZ_SIM_RENDER_ENGINE_BACKEND=ogre2
      - EGL_LOG_LEVEL=fatal
      # MESA_LOADER_DRIVER_OVERRIDE=radeonsi # Bu ayar bazen dri2 hatası verdirir, yoruma alındı.
      # GALLIUM_DRIVER=radeonsi

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # Kaynak kodlar ve scriptler
      - ../scripts:/home/yelpence/ros2_ws/scripts
      - ../sim:/home/yelpence/ros2_ws/sim
      - ../src:/home/yelpence/ros2_ws/src
      - ../.git:/home/yelpence/ros2_ws/.git:ro

      # ROS 2 Derleme izolasyonu
      # - /home/yelpence/ros2_ws/build
      # - /home/yelpence/ros2_ws/install

      # PX4 Derleme izolasyonu
      # PX4'ün host makinenizin içine build klasörü açmasını engeller.
      - /home/yelpence/ros2_ws/src/px4_autopilot/build

    devices:
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyAMA0:/dev/ttyAMA0

    group_add:
      - video
      - "992"

    stdin_open: true
    tty: true
    command: /bin/bash
