# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/home/osmancevik/PX4-Autopilot;/home/osmancevik/PX4-Autopilot/build/px4_fmu-v3_default")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_GROUPING "ALL_COMPONENTS_IN_ONE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEB_COMPONENT_INSTALL "YES")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "px4 built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "ZIP")
set(CPACK_INNOSETUP_ARCHITECTURE "x86")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/osmancevik/PX4-Autopilot/build/px4_fmu-v3_default;px4;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/osmancevik/PX4-Autopilot/cmake;/home/osmancevik/PX4-Autopilot/platforms/nuttx/cmake;/home/osmancevik/PX4-Autopilot/platforms/nuttx/cmake;/home/osmancevik/PX4-Autopilot/cmake/gtest/")
set(CPACK_NSIS_DISPLAY_NAME "px4-px4_fmu-v3_default 1.16.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "px4-px4_fmu-v3_default 1.16.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/arm-none-eabi-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/arm-none-eabi-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/osmancevik/PX4-Autopilot/build/px4_fmu-v3_default/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "daniel@agar.ca")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "px4 built using CMake")
set(CPACK_PACKAGE_FILE_NAME "px4-px4_fmu-v3_default-v1.16.1")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "px4-px4_fmu-v3_default 1.16.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "px4-px4_fmu-v3_default 1.16.1")
set(CPACK_PACKAGE_NAME "px4-px4_fmu-v3_default")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "px4")
set(CPACK_PACKAGE_VERSION "1.16.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "16")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_PACKAGING_INSTALL_PREFIX "")
set(CPACK_READELF_EXECUTABLE "/usr/bin/arm-none-eabi-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/osmancevik/PX4-Autopilot/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/osmancevik/PX4-Autopilot/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "ZIP;TBZ2")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/osmancevik/PX4-Autopilot/build/px4_fmu-v3_default/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "px4-px4_fmu-v3_default-v1.16.1-src")
set(CPACK_SYSTEM_NAME "Generic")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Generic")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/osmancevik/PX4-Autopilot/build/px4_fmu-v3_default/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
