[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_filters = time
; KEY WRITER — sadece NVS provision icin, ana firmwareyle karistirma
