/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/osmancevik/PX4-Autopilot/src/drivers/uavcan/libdronecan/dsdl/dronecan/sensors/rpm/1045.RPM.uavcan
 */

#ifndef DRONECAN_SENSORS_RPM_RPM_HPP_INCLUDED
#define DRONECAN_SENSORS_RPM_RPM_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# RPM reading in revolutions per minute
#

uint8 sensor_id

uint16 FLAGS_UNHEALTHY = 1 # Sensor is not healthy

uint16 flags

float32 rpm
******************************************************************************/

/********************* DSDL signature source definition ***********************
dronecan.sensors.rpm.RPM
saturated uint8 sensor_id
saturated uint16 flags
saturated float32 rpm
******************************************************************************/

#undef sensor_id
#undef flags
#undef rpm
#undef FLAGS_UNHEALTHY

namespace dronecan
{
namespace sensors
{
namespace rpm
{

template <int _tmpl>
struct UAVCAN_EXPORT RPM_
{
    typedef const RPM_<_tmpl>& ParameterType;
    typedef RPM_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
        typedef ::uavcan::IntegerSpec< 16, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > FLAGS_UNHEALTHY;
    };

    struct FieldTypes
    {
        typedef ::uavcan::IntegerSpec< 8, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > sensor_id;
        typedef ::uavcan::IntegerSpec< 16, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > flags;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > rpm;
    };

    enum
    {
        MinBitLen
            = FieldTypes::sensor_id::MinBitLen
            + FieldTypes::flags::MinBitLen
            + FieldTypes::rpm::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::sensor_id::MaxBitLen
            + FieldTypes::flags::MaxBitLen
            + FieldTypes::rpm::MaxBitLen
    };

    // Constants
    static const typename ::uavcan::StorageType< typename ConstantTypes::FLAGS_UNHEALTHY >::Type FLAGS_UNHEALTHY; // 1

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::sensor_id >::Type sensor_id;
    typename ::uavcan::StorageType< typename FieldTypes::flags >::Type flags;
    typename ::uavcan::StorageType< typename FieldTypes::rpm >::Type rpm;

    RPM_()
        : sensor_id()
        , flags()
        , rpm()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<56 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 1045 };

    static const char* getDataTypeFullName()
    {
        return "dronecan.sensors.rpm.RPM";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool RPM_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        sensor_id == rhs.sensor_id &&
        flags == rhs.flags &&
        rpm == rhs.rpm;
}

template <int _tmpl>
bool RPM_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(sensor_id, rhs.sensor_id) &&
        ::uavcan::areClose(flags, rhs.flags) &&
        ::uavcan::areClose(rpm, rhs.rpm);
}

template <int _tmpl>
int RPM_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::sensor_id::encode(self.sensor_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::flags::encode(self.flags, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::rpm::encode(self.rpm, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int RPM_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::sensor_id::decode(self.sensor_id, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::flags::decode(self.flags, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::rpm::decode(self.rpm, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature RPM_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x140707C09274F6E7ULL);

    FieldTypes::sensor_id::extendDataTypeSignature(signature);
    FieldTypes::flags::extendDataTypeSignature(signature);
    FieldTypes::rpm::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

template <int _tmpl>
const typename ::uavcan::StorageType< typename RPM_<_tmpl>::ConstantTypes::FLAGS_UNHEALTHY >::Type
    RPM_<_tmpl>::FLAGS_UNHEALTHY = 1U; // 1

/*
 * Final typedef
 */
typedef RPM_<0> RPM;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::dronecan::sensors::rpm::RPM > _uavcan_gdtr_registrator_RPM;

}

} // Namespace rpm
} // Namespace sensors
} // Namespace dronecan

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::dronecan::sensors::rpm::RPM >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::dronecan::sensors::rpm::RPM::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::dronecan::sensors::rpm::RPM >::stream(Stream& s, ::dronecan::sensors::rpm::RPM::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "sensor_id: ";
    YamlStreamer< ::dronecan::sensors::rpm::RPM::FieldTypes::sensor_id >::stream(s, obj.sensor_id, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "flags: ";
    YamlStreamer< ::dronecan::sensors::rpm::RPM::FieldTypes::flags >::stream(s, obj.flags, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "rpm: ";
    YamlStreamer< ::dronecan::sensors::rpm::RPM::FieldTypes::rpm >::stream(s, obj.rpm, level + 1);
}

}

namespace dronecan
{
namespace sensors
{
namespace rpm
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::dronecan::sensors::rpm::RPM::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::dronecan::sensors::rpm::RPM >::stream(s, obj, 0);
    return s;
}

} // Namespace rpm
} // Namespace sensors
} // Namespace dronecan

#endif // DRONECAN_SENSORS_RPM_RPM_HPP_INCLUDED