/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/osmancevik/PX4-Autopilot/msg/versioned/ArmingCheckReply.msg */


#pragma once


#include <uORB/uORB.h>

#include <uORB/topics/event.h>

#ifndef __cplusplus
#define ARMING_CHECK_REPLY_MESSAGE_VERSION 0
#define ARMING_CHECK_REPLY_HEALTH_COMPONENT_INDEX_NONE 0
#define ARMING_CHECK_REPLY_ORB_QUEUE_LENGTH 4

#endif


#ifdef __cplusplus
struct __EXPORT arming_check_reply_s {
#else
struct arming_check_reply_s {
#endif
	uint64_t timestamp;
	uint8_t request_id;
	uint8_t registration_id;
	uint8_t health_component_index;
	bool health_component_is_present;
	bool health_component_warning;
	bool health_component_error;
	bool can_arm_and_run;
	uint8_t num_events;
	bool mode_req_angular_velocity;
	bool mode_req_attitude;
	bool mode_req_local_alt;
	bool mode_req_local_position;
	bool mode_req_local_position_relaxed;
	bool mode_req_global_position;
	bool mode_req_mission;
	bool mode_req_home_position;
	bool mode_req_prevent_arming;
	bool mode_req_manual_control;
	uint8_t _padding0[6]; // required for logger
	struct event_s events[5];


#ifdef __cplusplus
	static constexpr uint32_t MESSAGE_VERSION = 0;
	static constexpr uint8_t HEALTH_COMPONENT_INDEX_NONE = 0;
	static constexpr uint8_t ORB_QUEUE_LENGTH = 4;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using ArmingCheckReply = arming_check_reply_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(arming_check_reply);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const arming_check_reply_s& message);
#endif
