/****************************************************************************
 *
 *   Copyright (C) 2013-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/* Auto-generated by genmsg_cpp from file /home/osmancevik/PX4-Autopilot/msg/versioned/RegisterExtComponentRequest.msg */


#pragma once


#include <uORB/uORB.h>


#ifndef __cplusplus
#define REGISTER_EXT_COMPONENT_REQUEST_MESSAGE_VERSION 0
#define REGISTER_EXT_COMPONENT_REQUEST_LATEST_PX4_ROS2_API_VERSION 1
#define REGISTER_EXT_COMPONENT_REQUEST_ORB_QUEUE_LENGTH 2

#endif


#ifdef __cplusplus
struct __EXPORT register_ext_component_request_s {
#else
struct register_ext_component_request_s {
#endif
	uint64_t timestamp;
	uint64_t request_id;
	uint16_t px4_ros2_api_version;
	char name[25];
	bool register_arming_check;
	bool register_mode;
	bool register_mode_executor;
	bool enable_replace_internal_mode;
	uint8_t replace_internal_mode;
	bool activate_mode_immediately;
	uint8_t _padding0[7]; // required for logger


#ifdef __cplusplus
	static constexpr uint32_t MESSAGE_VERSION = 0;
	static constexpr uint16_t LATEST_PX4_ROS2_API_VERSION = 1;
	static constexpr uint8_t ORB_QUEUE_LENGTH = 2;

#endif
};

#ifdef __cplusplus
namespace px4 {
	namespace msg {
		using RegisterExtComponentRequest = register_ext_component_request_s;
	} // namespace msg
} // namespace px4
#endif

/* register this as object request broker structure */
ORB_DECLARE(register_ext_component_request);


#ifdef __cplusplus
void print_message(const orb_metadata *meta, const register_ext_component_request_s& message);
#endif
