/****************************************************************************
 *
 *   Copyright (C) 2021-2022 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/


#pragma once

#include <stddef.h>

#include <uORB/uORB.h>

static constexpr size_t ORB_TOPICS_COUNT{292};
static constexpr size_t orb_topics_count() { return ORB_TOPICS_COUNT; }

/*
 * Returns array of topics metadata
 */
extern const struct orb_metadata *const *orb_get_topics() __EXPORT;

enum class ORB_ID : orb_id_size_t {
	ackermann_velocity_setpoint = 0,
	action_request = 1,
	actuator_armed = 2,
	actuator_controls_status_0 = 3,
	actuator_controls_status_1 = 4,
	actuator_motors = 5,
	actuator_outputs = 6,
	actuator_outputs_debug = 7,
	actuator_outputs_sim = 8,
	actuator_servos = 9,
	actuator_servos_trim = 10,
	actuator_test = 11,
	adc_report = 12,
	airspeed = 13,
	airspeed_validated = 14,
	airspeed_wind = 15,
	arming_check_reply = 16,
	arming_check_request = 17,
	autotune_attitude_control_status = 18,
	aux_global_position = 19,
	battery_status = 20,
	button_event = 21,
	camera_capture = 22,
	camera_status = 23,
	camera_trigger = 24,
	can_interface_status = 25,
	cellular_status = 26,
	collision_constraints = 27,
	config_control_setpoints = 28,
	config_overrides = 29,
	config_overrides_request = 30,
	control_allocator_status = 31,
	cpuload = 32,
	dataman_request = 33,
	dataman_response = 34,
	debug_array = 35,
	debug_key_value = 36,
	debug_value = 37,
	debug_vect = 38,
	differential_pressure = 39,
	differential_velocity_setpoint = 40,
	distance_sensor = 41,
	distance_sensor_mode_change_request = 42,
	ekf2_timestamps = 43,
	esc_report = 44,
	esc_serial_passthru = 45,
	esc_status = 46,
	estimator_aid_src_airspeed = 47,
	estimator_aid_src_aux_global_position = 48,
	estimator_aid_src_aux_vel = 49,
	estimator_aid_src_baro_hgt = 50,
	estimator_aid_src_drag = 51,
	estimator_aid_src_ev_hgt = 52,
	estimator_aid_src_ev_pos = 53,
	estimator_aid_src_ev_vel = 54,
	estimator_aid_src_ev_yaw = 55,
	estimator_aid_src_fake_hgt = 56,
	estimator_aid_src_fake_pos = 57,
	estimator_aid_src_gnss_hgt = 58,
	estimator_aid_src_gnss_pos = 59,
	estimator_aid_src_gnss_vel = 60,
	estimator_aid_src_gnss_yaw = 61,
	estimator_aid_src_gravity = 62,
	estimator_aid_src_mag = 63,
	estimator_aid_src_optical_flow = 64,
	estimator_aid_src_rng_hgt = 65,
	estimator_aid_src_sideslip = 66,
	estimator_attitude = 67,
	estimator_baro_bias = 68,
	estimator_bias3d = 69,
	estimator_ev_pos_bias = 70,
	estimator_event_flags = 71,
	estimator_global_position = 72,
	estimator_gnss_hgt_bias = 73,
	estimator_gps_status = 74,
	estimator_innovation_test_ratios = 75,
	estimator_innovation_variances = 76,
	estimator_innovations = 77,
	estimator_local_position = 78,
	estimator_odometry = 79,
	estimator_optical_flow_vel = 80,
	estimator_selector_status = 81,
	estimator_sensor_bias = 82,
	estimator_states = 83,
	estimator_status = 84,
	estimator_status_flags = 85,
	estimator_wind = 86,
	event = 87,
	external_ins_attitude = 88,
	external_ins_global_position = 89,
	external_ins_local_position = 90,
	failsafe_flags = 91,
	failure_detector_status = 92,
	figure_eight_status = 93,
	flaps_setpoint = 94,
	flight_phase_estimation = 95,
	follow_target = 96,
	follow_target_estimator = 97,
	follow_target_status = 98,
	fuel_tank_status = 99,
	fw_virtual_attitude_setpoint = 100,
	generator_status = 101,
	geofence_result = 102,
	geofence_status = 103,
	gimbal_controls = 104,
	gimbal_device_attitude_status = 105,
	gimbal_device_information = 106,
	gimbal_device_set_attitude = 107,
	gimbal_manager_information = 108,
	gimbal_manager_set_attitude = 109,
	gimbal_manager_set_manual_control = 110,
	gimbal_manager_status = 111,
	gimbal_v1_command = 112,
	goto_setpoint = 113,
	gpio_config = 114,
	gpio_in = 115,
	gpio_out = 116,
	gpio_request = 117,
	gps_dump = 118,
	gps_inject_data = 119,
	gripper = 120,
	health_report = 121,
	heater_status = 122,
	home_position = 123,
	hover_thrust_estimate = 124,
	input_rc = 125,
	internal_combustion_engine_control = 126,
	internal_combustion_engine_status = 127,
	iridiumsbd_status = 128,
	irlock_report = 129,
	landing_gear = 130,
	landing_gear_wheel = 131,
	landing_target_innovations = 132,
	landing_target_pose = 133,
	launch_detection_status = 134,
	led_control = 135,
	log_message = 136,
	logger_status = 137,
	mag_worker_data = 138,
	magnetometer_bias_estimate = 139,
	manual_control_input = 140,
	manual_control_setpoint = 141,
	manual_control_switches = 142,
	mavlink_log = 143,
	mavlink_tunnel = 144,
	mc_virtual_attitude_setpoint = 145,
	message_format_request = 146,
	message_format_response = 147,
	mission = 148,
	mission_result = 149,
	mode_completed = 150,
	mount_orientation = 151,
	navigator_mission_item = 152,
	navigator_status = 153,
	npfg_status = 154,
	obstacle_distance = 155,
	obstacle_distance_fused = 156,
	offboard_control_mode = 157,
	onboard_computer_status = 158,
	open_drone_id_arm_status = 159,
	open_drone_id_operator_id = 160,
	open_drone_id_self_id = 161,
	open_drone_id_system = 162,
	orb_multitest = 163,
	orb_test = 164,
	orb_test_large = 165,
	orb_test_medium = 166,
	orb_test_medium_multi = 167,
	orb_test_medium_queue = 168,
	orb_test_medium_queue_poll = 169,
	orb_test_medium_wrap_around = 170,
	orbit_status = 171,
	parameter_primary_set_value_request = 172,
	parameter_primary_set_value_response = 173,
	parameter_remote_set_value_request = 174,
	parameter_remote_set_value_response = 175,
	parameter_reset_request = 176,
	parameter_set_used_request = 177,
	parameter_set_value_request = 178,
	parameter_set_value_response = 179,
	parameter_update = 180,
	ping = 181,
	position_controller_landing_status = 182,
	position_controller_status = 183,
	position_setpoint = 184,
	position_setpoint_triplet = 185,
	power_button_state = 186,
	power_monitor = 187,
	pps_capture = 188,
	pure_pursuit_status = 189,
	pwm_input = 190,
	px4io_status = 191,
	qshell_req = 192,
	qshell_retval = 193,
	radio_status = 194,
	rate_ctrl_status = 195,
	rc_channels = 196,
	rc_parameter_map = 197,
	register_ext_component_reply = 198,
	register_ext_component_request = 199,
	rover_attitude_setpoint = 200,
	rover_attitude_status = 201,
	rover_position_setpoint = 202,
	rover_rate_setpoint = 203,
	rover_rate_status = 204,
	rover_steering_setpoint = 205,
	rover_throttle_setpoint = 206,
	rover_velocity_status = 207,
	rpm = 208,
	rtl_status = 209,
	rtl_time_estimate = 210,
	safety_button = 211,
	satellite_info = 212,
	sensor_accel = 213,
	sensor_accel_fifo = 214,
	sensor_airflow = 215,
	sensor_baro = 216,
	sensor_combined = 217,
	sensor_correction = 218,
	sensor_gnss_relative = 219,
	sensor_gps = 220,
	sensor_gyro = 221,
	sensor_gyro_fft = 222,
	sensor_gyro_fifo = 223,
	sensor_hygrometer = 224,
	sensor_mag = 225,
	sensor_optical_flow = 226,
	sensor_preflight_mag = 227,
	sensor_selection = 228,
	sensor_uwb = 229,
	sensors_status_baro = 230,
	sensors_status_imu = 231,
	sensors_status_mag = 232,
	spoilers_setpoint = 233,
	system_power = 234,
	takeoff_status = 235,
	task_stack_info = 236,
	tecs_status = 237,
	telemetry_status = 238,
	tiltrotor_extra_controls = 239,
	timesync_status = 240,
	trajectory_setpoint = 241,
	trajectory_setpoint6dof = 242,
	transponder_report = 243,
	tune_control = 244,
	uavcan_parameter_request = 245,
	uavcan_parameter_value = 246,
	ulog_stream = 247,
	ulog_stream_ack = 248,
	unregister_ext_component = 249,
	vehicle_acceleration = 250,
	vehicle_air_data = 251,
	vehicle_angular_acceleration_setpoint = 252,
	vehicle_angular_velocity = 253,
	vehicle_angular_velocity_groundtruth = 254,
	vehicle_attitude = 255,
	vehicle_attitude_groundtruth = 256,
	vehicle_attitude_setpoint = 257,
	vehicle_command = 258,
	vehicle_command_ack = 259,
	vehicle_command_mode_executor = 260,
	vehicle_constraints = 261,
	vehicle_control_mode = 262,
	vehicle_global_position = 263,
	vehicle_global_position_groundtruth = 264,
	vehicle_gps_position = 265,
	vehicle_imu = 266,
	vehicle_imu_status = 267,
	vehicle_land_detected = 268,
	vehicle_local_position = 269,
	vehicle_local_position_groundtruth = 270,
	vehicle_local_position_setpoint = 271,
	vehicle_magnetometer = 272,
	vehicle_mocap_odometry = 273,
	vehicle_odometry = 274,
	vehicle_optical_flow = 275,
	vehicle_optical_flow_vel = 276,
	vehicle_rates_setpoint = 277,
	vehicle_roi = 278,
	vehicle_status = 279,
	vehicle_thrust_setpoint = 280,
	vehicle_thrust_setpoint_virtual_fw = 281,
	vehicle_thrust_setpoint_virtual_mc = 282,
	vehicle_torque_setpoint = 283,
	vehicle_torque_setpoint_virtual_fw = 284,
	vehicle_torque_setpoint_virtual_mc = 285,
	vehicle_visual_odometry = 286,
	velocity_limits = 287,
	vtol_vehicle_status = 288,
	wheel_encoders = 289,
	wind = 290,
	yaw_estimator_status = 291,

	INVALID
};

const struct orb_metadata *get_orb_meta(ORB_ID id);
